application: lexical-period-752
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: project2.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest